name: Gradle Setup
description: Setup Java and Gradle for KMP builds with remote cache
inputs:
  cache_read_only:
    description: 'Whether Gradle cache is read-only'
    default: 'true'
  java_version:
    description: 'JDK version'
    default: '21'
  gradle_encryption_key:
    description: 'Encryption key for Gradle remote cache'
    required: false
  develocity_access_key:
    description: 'Access key for the OSS Community Develocity Instance (Build Scan publishing and remote cache writes)'
    required: false
runs:
  using: composite
  steps:
    - name: Copy CI Gradle properties
      shell: bash
      run: mkdir -p ~/.gradle && cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

    - name: Set up JDK ${{ inputs.java_version }}
      uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
      with:
        java-version: ${{ inputs.java_version }}
        distribution: temurin

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      with:
        cache-read-only: ${{ inputs.cache_read_only }}
        cache-encryption-key: ${{ inputs.gradle_encryption_key }}
        cache-cleanup: on-success
        add-job-summary: always
        develocity-access-key: ${{ inputs.develocity_access_key }}
